### PR TITLE
Adding Python 3.8 and 3.9 compatibility (and adding 3.13-dev to the CI matrix)

### PR DESCRIPTION
**Pull request by dem1995**
-Added Python 3.8 and 3.9 support through optional dependencies on `typing-extensions`. 

-Updated `pyupgrade`, `flake`, etc. versions accordingly (i.e. down to 3.8).

-Added a couple of ignores to `flake` (# E701 and E704) due to it and Black having different opinions on multiline empty classes.

Initial merge might break CI due to CodeCov token in `CodeCov.yaml`; this was necessary to get the CodeCov portion of the CI working in my experience (see https://community.codecov.com/t/upload-issues-unable-to-locate-build-via-github-actions-api/3954).

### CODE REVIEW

**Comment by antonagestam** [comment]
Sorry but this is just too unfocused to review.

**Comment by antonagestam** [comment]
@dem1995 I'm really glad you want to contribute to this repository, but changes need to come in much smaller increments where each PR is an atomic change. This PR changes almost every single file in the repository, so it becomes impossible to review properly.

**Comment by dem1995** [comment]
@antonagestam entirely understandable. Would you prefer a clean PR to prep the the automated testing followed by a clean PR with the 3.8/3.9 support? Inevitably the internal commits will be more atomic and less meandering as well.

**Comment by antonagestam** [comment]
@dem1995 Please also feel free to open issues for the things you would like to improve so that there aren't surprises after you've invested time into implementation. For Python 3.9 and 3.8, I'm not very excited about bringing support for those versions as they're both quite close to EOL.

**Pull request closed without merging**
